// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application elasticityimplicit.

#include "ElasticityImplicitData2DLinear.hh"

const int pylith::feassemble::ElasticityImplicitData2DLinear::_spaceDim = 2;

const int pylith::feassemble::ElasticityImplicitData2DLinear::_cellDim = 2;

const int pylith::feassemble::ElasticityImplicitData2DLinear::_numVertices = 3;

const int pylith::feassemble::ElasticityImplicitData2DLinear::_numCells = 1;

const int pylith::feassemble::ElasticityImplicitData2DLinear::_numBasis = 3;

const int pylith::feassemble::ElasticityImplicitData2DLinear::_numQuadPts = 1;

const char* pylith::feassemble::ElasticityImplicitData2DLinear::_matType = "ElasticPlaneStrain";

const char* pylith::feassemble::ElasticityImplicitData2DLinear::_matDBFilename = "data/elasticplanestrain.spatialdb";

const int pylith::feassemble::ElasticityImplicitData2DLinear::_matId = 0;

const char* pylith::feassemble::ElasticityImplicitData2DLinear::_matLabel = "elastic strain 2-D";

const double pylith::feassemble::ElasticityImplicitData2DLinear::_dt =   1.00000000e-02;

const double pylith::feassemble::ElasticityImplicitData2DLinear::_vertices[] = {
  2.00000000e-01, -4.00000000e-01,
  3.00000000e-01,  5.00000000e-01,
 -1.00000000e+00, -2.00000000e-01,
};

const int pylith::feassemble::ElasticityImplicitData2DLinear::_cells[] = {
0,1,2,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_quadPts[] = {
  3.33333333e-01,  3.33333333e-01,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_quadWts[] = {
  5.00000000e-01,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_basis[] = {
  3.33333333e-01,  3.33333333e-01,
  3.33333333e-01,};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_basisDeriv[] = {
 -1.00000000e+00, -1.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_fieldTpdt[] = {
  1.90000000e+00, -9.00000000e-01,
  1.40000000e+00,  1.50000000e+00,
  5.00000000e-01, -9.00000000e-01,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_fieldT[] = {
  1.60000000e+00, -8.00000000e-01,
  9.00000000e-01,  7.00000000e-01,
 -2.00000000e-01, -1.10000000e+00,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_fieldTmdt[] = {
  8.00000000e-01,  1.00000000e-01,
  5.00000000e-01,  3.00000000e-01,
 -1.00000000e-01, -6.00000000e-01,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_valsResidual[] = {
 -4.20750000e+10, -2.88750000e+10,
  3.96000000e+10,  2.47500000e+09,
  2.47500000e+09,  2.64000000e+10,
};

const double pylith::feassemble::ElasticityImplicitData2DLinear::_valsJacobian[] = {
  5.77500000e+10,  2.47500000e+10,
 -4.95000000e+10, -8.25000000e+09,
 -8.25000000e+09, -1.65000000e+10,
  2.47500000e+10,  5.77500000e+10,
 -1.65000000e+10, -8.25000000e+09,
 -8.25000000e+09, -4.95000000e+10,
 -4.95000000e+10, -1.65000000e+10,
  4.95000000e+10,  0.00000000e+00,
  0.00000000e+00,  1.65000000e+10,
 -8.25000000e+09, -8.25000000e+09,
  0.00000000e+00,  8.25000000e+09,
  8.25000000e+09,  0.00000000e+00,
 -8.25000000e+09, -8.25000000e+09,
  0.00000000e+00,  8.25000000e+09,
  8.25000000e+09,  0.00000000e+00,
 -1.65000000e+10, -4.95000000e+10,
  1.65000000e+10,  0.00000000e+00,
  0.00000000e+00,  4.95000000e+10,
};

pylith::feassemble::ElasticityImplicitData2DLinear::ElasticityImplicitData2DLinear(void)
{ // constructor
  spaceDim = _spaceDim;
  cellDim = _cellDim;
  numVertices = _numVertices;
  numCells = _numCells;
  numBasis = _numBasis;
  numQuadPts = _numQuadPts;
  matType = const_cast<char*>(_matType);
  matDBFilename = const_cast<char*>(_matDBFilename);
  matId = _matId;
  matLabel = const_cast<char*>(_matLabel);
  dt = _dt;
  vertices = const_cast<double*>(_vertices);
  cells = const_cast<int*>(_cells);
  quadPts = const_cast<double*>(_quadPts);
  quadWts = const_cast<double*>(_quadWts);
  basis = const_cast<double*>(_basis);
  basisDeriv = const_cast<double*>(_basisDeriv);
  fieldTpdt = const_cast<double*>(_fieldTpdt);
  fieldT = const_cast<double*>(_fieldT);
  fieldTmdt = const_cast<double*>(_fieldTmdt);
  valsResidual = const_cast<double*>(_valsResidual);
  valsJacobian = const_cast<double*>(_valsJacobian);
} // constructor

pylith::feassemble::ElasticityImplicitData2DLinear::~ElasticityImplicitData2DLinear(void)
{}


// End of file
