// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application itnegratorinertia1dquadratic.

#include "IntegratorDataInertia1DQuadratic.hh"

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_numVertices = 3;

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_spaceDim = 1;

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_numCells = 1;

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_cellDim = 1;

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_numCorners = 3;

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_numQuadPts = 2;

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_fiberDim = 1;

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_vertices[] = {
 -2.50000000e-01,
  8.75000000e-01,
  2.00000000e+00,
};

const int pylith::feassemble::IntegratorDataInertia1DQuadratic::_cells[] = {
       0,       1,       2,
};

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_quadPts[] = {
 -5.77350269e-01,
  5.77350269e-01,
};

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_quadWts[] = {
  1.00000000e+00,  1.00000000e+00,
};

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_basis[] = {
  4.55341801e-01,
  6.66666667e-01,
 -1.22008468e-01,
 -1.22008468e-01,
  6.66666667e-01,
  4.55341801e-01,
};

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_basisDeriv[] = {
 -1.07735027e+00,
  1.15470054e+00,
 -7.73502692e-02,
  7.73502692e-02,
 -1.15470054e+00,
  1.07735027e+00,
};

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_fieldIn[] = {
  1.20000000e+00,
  1.50000000e+00,
 -8.00000000e-01,
};

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_valsAction[] = {
  7.75000000e-01,
  1.60000000e+00,
  2.50000000e-02,
};

const double pylith::feassemble::IntegratorDataInertia1DQuadratic::_valsMatrix[] = {
  2.50000000e-01,
  2.50000000e-01,
 -1.25000000e-01,
  2.50000000e-01,
  1.00000000e+00,
  2.50000000e-01,
 -1.25000000e-01,
  2.50000000e-01,
  2.50000000e-01,
};

pylith::feassemble::IntegratorDataInertia1DQuadratic::IntegratorDataInertia1DQuadratic(void)
{ // constructor
  numVertices = _numVertices;
  spaceDim = _spaceDim;
  numCells = _numCells;
  cellDim = _cellDim;
  numCorners = _numCorners;
  numQuadPts = _numQuadPts;
  fiberDim = _fiberDim;
  vertices = const_cast<double*>(_vertices);
  cells = const_cast<int*>(_cells);
  quadPts = const_cast<double*>(_quadPts);
  quadWts = const_cast<double*>(_quadWts);
  basis = const_cast<double*>(_basis);
  basisDeriv = const_cast<double*>(_basisDeriv);
  fieldIn = const_cast<double*>(_fieldIn);
  valsAction = const_cast<double*>(_valsAction);
  valsMatrix = const_cast<double*>(_valsMatrix);
} // constructor

pylith::feassemble::IntegratorDataInertia1DQuadratic::~IntegratorDataInertia1DQuadratic(void)
{}


// End of file
