// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application quadrature2din3dlinear.

#include "QuadratureData2Din3DLinearXZ.hh"

const int pylith::feassemble::QuadratureData2Din3DLinearXZ::_numVertices = 3;

const int pylith::feassemble::QuadratureData2Din3DLinearXZ::_spaceDim = 3;

const int pylith::feassemble::QuadratureData2Din3DLinearXZ::_numCells = 1;

const int pylith::feassemble::QuadratureData2Din3DLinearXZ::_cellDim = 2;

const int pylith::feassemble::QuadratureData2Din3DLinearXZ::_numBasis = 3;

const int pylith::feassemble::QuadratureData2Din3DLinearXZ::_numQuadPts = 1;

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_vertices[] = {
  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
 -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
};

const int pylith::feassemble::QuadratureData2Din3DLinearXZ::_cells[] = {
       0,       1,       2,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_quadPtsRef[] = {
  3.33333333e-01,  3.33333333e-01,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_quadWts[] = {
  5.00000000e-01,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_quadPts[] = {
 -3.33333333e-01,  0.00000000e+00,  3.33333333e-01,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_basisVert[] = {
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
  1.00000000e+00,};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_basisDerivVert[] = {
 -1.00000000e+00, -1.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
 -1.00000000e+00, -1.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
 -1.00000000e+00, -1.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_jacobianVert[] = {
 -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
 -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
 -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_jacobianDetVert[] = {
  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_basisQuad[] = {
  3.33333333e-01,  3.33333333e-01,
  3.33333333e-01,};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_basisDerivQuad[] = {
 -1.00000000e+00, -1.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_jacobianQuad[] = {
 -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_jacobianDetQuad[] = {
  1.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DLinearXZ::_jacobianInvQuad[] = {
 -1.00000000e+00, -0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
};

pylith::feassemble::QuadratureData2Din3DLinearXZ::QuadratureData2Din3DLinearXZ(void)
{ // constructor
  numVertices = _numVertices;
  spaceDim = _spaceDim;
  numCells = _numCells;
  cellDim = _cellDim;
  numBasis = _numBasis;
  numQuadPts = _numQuadPts;
  vertices = const_cast<double*>(_vertices);
  cells = const_cast<int*>(_cells);
  quadPtsRef = const_cast<double*>(_quadPtsRef);
  quadWts = const_cast<double*>(_quadWts);
  quadPts = const_cast<double*>(_quadPts);
  basisVert = const_cast<double*>(_basisVert);
  basisDerivVert = const_cast<double*>(_basisDerivVert);
  jacobianVert = const_cast<double*>(_jacobianVert);
  jacobianDetVert = const_cast<double*>(_jacobianDetVert);
  basisQuad = const_cast<double*>(_basisQuad);
  basisDerivQuad = const_cast<double*>(_basisDerivQuad);
  jacobianQuad = const_cast<double*>(_jacobianQuad);
  jacobianDetQuad = const_cast<double*>(_jacobianDetQuad);
  jacobianInvQuad = const_cast<double*>(_jacobianInvQuad);
} // constructor

pylith::feassemble::QuadratureData2Din3DLinearXZ::~QuadratureData2Din3DLinearXZ(void)
{}


// End of file
