// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application quadrature2din3dquadratic.

#include "QuadratureData2Din3DQuadratic.hh"

const int pylith::feassemble::QuadratureData2Din3DQuadratic::_numVertices = 6;

const int pylith::feassemble::QuadratureData2Din3DQuadratic::_spaceDim = 3;

const int pylith::feassemble::QuadratureData2Din3DQuadratic::_numCells = 1;

const int pylith::feassemble::QuadratureData2Din3DQuadratic::_cellDim = 2;

const int pylith::feassemble::QuadratureData2Din3DQuadratic::_numBasis = 6;

const int pylith::feassemble::QuadratureData2Din3DQuadratic::_numQuadPts = 3;

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_vertices[] = {
  2.00000000e+00, -5.00000000e-01, -5.00000000e-01,
  5.00000000e-01,  3.00000000e+00,  0.00000000e+00,
 -5.00000000e-01,  0.00000000e+00,  2.00000000e+00,
  1.30000000e+00,  1.20000000e+00, -3.00000000e-01,
  1.00000000e-01,  1.40000000e+00,  9.00000000e-01,
  8.00000000e-01, -3.00000000e-01,  7.00000000e-01,
};

const int pylith::feassemble::QuadratureData2Din3DQuadratic::_cells[] = {
       0,       1,       2,       3,       4,       5,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_quadPtsRef[] = {
  6.66666667e-01,  1.66666667e-01,
  1.66666667e-01,  6.66666667e-01,
  1.66666667e-01,  1.66666667e-01,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_quadWts[] = {
  1.66666667e-01,  1.66666667e-01,  1.66666667e-01,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_quadPts[] = {
  6.55555556e-01,  1.84444444e+00,  1.77777778e-01,
  1.55555556e-01,  3.44444444e-01,  1.17777778e+00,
  1.38888889e+00,  1.11111111e-01, -5.55555556e-02,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_basisVert[] = {
  1.00000000e+00, -0.00000000e+00,
 -0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
 -0.00000000e+00,  1.00000000e+00,
 -0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
 -0.00000000e+00, -0.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
 -0.00000000e+00,  1.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00, -0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
 -0.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_basisDerivVert[] = {
 -3.00000000e+00, -3.00000000e+00,
 -1.00000000e+00,  0.00000000e+00,
  0.00000000e+00, -1.00000000e+00,
  4.00000000e+00, -0.00000000e+00,
  0.00000000e+00,  0.00000000e+00,
 -0.00000000e+00,  4.00000000e+00,
  1.00000000e+00,  1.00000000e+00,
  3.00000000e+00,  0.00000000e+00,
  0.00000000e+00, -1.00000000e+00,
 -4.00000000e+00, -4.00000000e+00,
  0.00000000e+00,  4.00000000e+00,
 -0.00000000e+00,  0.00000000e+00,
  1.00000000e+00,  1.00000000e+00,
 -1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  3.00000000e+00,
  0.00000000e+00, -0.00000000e+00,
  4.00000000e+00,  0.00000000e+00,
 -4.00000000e+00, -4.00000000e+00,
 -1.00000000e+00, -1.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00, -1.00000000e+00,
  0.00000000e+00, -2.00000000e+00,
  0.00000000e+00,  2.00000000e+00,
 -0.00000000e+00,  2.00000000e+00,
 -1.00000000e+00, -1.00000000e+00,
 -1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
  2.00000000e+00, -0.00000000e+00,
  2.00000000e+00,  0.00000000e+00,
 -2.00000000e+00,  0.00000000e+00,
  1.00000000e+00,  1.00000000e+00,
  1.00000000e+00,  0.00000000e+00,
  0.00000000e+00,  1.00000000e+00,
 -2.00000000e+00, -2.00000000e+00,
  2.00000000e+00,  2.00000000e+00,
 -2.00000000e+00, -2.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_jacobianVert[] = {
 -1.30000000e+00,  3.30000000e+00,  3.00000000e-01,
 -2.30000000e+00,  3.00000000e-01,  2.30000000e+00,
 -1.70000000e+00,  3.70000000e+00,  7.00000000e-01,
 -2.30000000e+00,  3.00000000e-01,  2.30000000e+00,
 -1.30000000e+00,  3.30000000e+00,  3.00000000e-01,
 -2.70000000e+00,  7.00000000e-01,  2.70000000e+00,
 -1.50000000e+00,  3.50000000e+00,  5.00000000e-01,
 -2.30000000e+00,  3.00000000e-01,  2.30000000e+00,
 -1.30000000e+00,  3.30000000e+00,  3.00000000e-01,
 -2.50000000e+00,  5.00000000e-01,  2.50000000e+00,
 -1.50000000e+00,  3.50000000e+00,  5.00000000e-01,
 -2.50000000e+00,  5.00000000e-01,  2.50000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_jacobianDetVert[] = {
  1.06480045e+01,  1.17549989e+01,  1.21235308e+01,  1.12008928e+01,  1.13850780e+01,  1.19373364e+01,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_basisQuad[] = {
 -1.11111111e-01,  2.22222222e-01,
 -1.11111111e-01,  4.44444444e-01,
  4.44444444e-01,  1.11111111e-01,
 -1.11111111e-01, -1.11111111e-01,
  2.22222222e-01,  1.11111111e-01,
  4.44444444e-01,  4.44444444e-01,
  2.22222222e-01, -1.11111111e-01,
 -1.11111111e-01,  4.44444444e-01,
  1.11111111e-01,  4.44444444e-01,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_basisDerivQuad[] = {
  3.33333333e-01,  3.33333333e-01,
  1.66666667e+00,  0.00000000e+00,
  0.00000000e+00, -3.33333333e-01,
 -2.00000000e+00, -2.66666667e+00,
  6.66666667e-01,  2.66666667e+00,
 -6.66666667e-01,  0.00000000e+00,
  3.33333333e-01,  3.33333333e-01,
 -3.33333333e-01,  0.00000000e+00,
  0.00000000e+00,  1.66666667e+00,
  0.00000000e+00, -6.66666667e-01,
  2.66666667e+00,  6.66666667e-01,
 -2.66666667e+00, -2.00000000e+00,
 -1.66666667e+00, -1.66666667e+00,
 -3.33333333e-01,  0.00000000e+00,
  0.00000000e+00, -3.33333333e-01,
  2.00000000e+00, -6.66666667e-01,
  6.66666667e-01,  6.66666667e-01,
 -6.66666667e-01,  2.00000000e+00,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_jacobianQuad[] = {
 -1.56666667e+00,  3.56666667e+00,  5.66666667e-01,
 -2.36666667e+00,  3.66666667e-01,  2.36666667e+00,
 -1.36666667e+00,  3.36666667e+00,  3.66666667e-01,
 -2.56666667e+00,  5.66666667e-01,  2.56666667e+00,
 -1.36666667e+00,  3.36666667e+00,  3.66666667e-01,
 -2.36666667e+00,  3.66666667e-01,  2.36666667e+00,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_jacobianDetQuad[] = {
  1.16307065e+01,  1.18149623e+01,  1.10776050e+01,
};

const double pylith::feassemble::QuadratureData2Din3DQuadratic::_jacobianInvQuad[] = {
  4.66101695e-02, -4.53389831e-01,
  3.00847458e-01, -1.99152542e-01,
 -4.45344130e-02,  4.33198381e-01,
  7.20338983e-02, -4.27966102e-01,
  3.26271186e-01, -1.73728814e-01,
 -6.71936759e-02,  3.99209486e-01,
  4.91071429e-02, -4.50892857e-01,
  3.16964286e-01, -1.83035714e-01,
 -4.68085106e-02,  4.29787234e-01,
};

pylith::feassemble::QuadratureData2Din3DQuadratic::QuadratureData2Din3DQuadratic(void)
{ // constructor
  numVertices = _numVertices;
  spaceDim = _spaceDim;
  numCells = _numCells;
  cellDim = _cellDim;
  numBasis = _numBasis;
  numQuadPts = _numQuadPts;
  vertices = const_cast<double*>(_vertices);
  cells = const_cast<int*>(_cells);
  quadPtsRef = const_cast<double*>(_quadPtsRef);
  quadWts = const_cast<double*>(_quadWts);
  quadPts = const_cast<double*>(_quadPts);
  basisVert = const_cast<double*>(_basisVert);
  basisDerivVert = const_cast<double*>(_basisDerivVert);
  jacobianVert = const_cast<double*>(_jacobianVert);
  jacobianDetVert = const_cast<double*>(_jacobianDetVert);
  basisQuad = const_cast<double*>(_basisQuad);
  basisDerivQuad = const_cast<double*>(_basisDerivQuad);
  jacobianQuad = const_cast<double*>(_jacobianQuad);
  jacobianDetQuad = const_cast<double*>(_jacobianDetQuad);
  jacobianInvQuad = const_cast<double*>(_jacobianInvQuad);
} // constructor

pylith::feassemble::QuadratureData2Din3DQuadratic::~QuadratureData2Din3DQuadratic(void)
{}


// End of file
