# =================================================================================================
# This code is part of PyLith, developed through the Computational Infrastructure
# for Geodynamics (https://github.com/geodynamics/pylith).
#
# Copyright (c) 2010-2026, University of California, Davis and the PyLith Development Team.
# All rights reserved.
#
# See https://mit-license.org/ and LICENSE.md and for license information. 
# =================================================================================================


subpackage = petsc
include $(top_srcdir)/subpackage.am

subpkginclude_HEADERS = \
	Application.hh \
	ErrorHandler.hh \
	EventLogger.hh \
	EventLogger.icc \
	PetscOptions.hh \
	PetscVersion.hh \
	TSAdaptImpulse.hh \
	TSMonitor.hh \
	SNESMonitor.hh \
	KSPMonitor.hh \
	petsc_types.h \
	petscfwd.hh

dist_noinst_HEADERS =


# End of file
