c -*- Fortran -*-
c
c~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c
c                             Charles A. Williams
c                       Rensselaer Polytechnic Institute
c                        (C) 2004  All Rights Reserved
c
c  Copyright 2004 Rensselaer Polytechnic Institute.
c  All worldwide rights reserved.  A license to use, copy, modify and
c  distribute this software for non-commercial research purposes only
c  is hereby granted, provided that this copyright notice and
c  accompanying disclaimer is not modified or removed from the software.
c
c  DISCLAIMER:  The software is distributed "AS IS" without any express
c  or implied warranty, including but not limited to, any implied
c  warranties of merchantability or fitness for a particular purpose
c  or any warranty of non-infringement of any current or pending patent
c  rights.  The authors of the software make no representations about
c  the suitability of this software for any particular purpose.  The
c  entire risk as to the quality and performance of the software is with
c  the user.  Should the software prove defective, the user assumes the
c  cost of all necessary servicing, repair or correction.  In
c  particular, neither Rensselaer Polytechnic Institute, nor the authors
c  of the software are liable for any indirect, special, consequential,
c  or incidental damages related to the software, to the maximum extent
c  the law permits.
c
c~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c
c...  td_strs_mat_ext.inc:  A header that lists the external routine
c     names to be called from stress_mat_drv.
c
      external  td_strs_mat_1, td_strs_mat_2, td_strs_mat_3
      external  td_strs_mat_4, td_strs_mat_5, td_strs_mat_6
      external  td_strs_mat_7, td_strs_mat_8, td_strs_mat_9
      external td_strs_mat_10,td_strs_mat_11,td_strs_mat_12
      external td_strs_mat_13,td_strs_mat_14,td_strs_mat_15
      external td_strs_mat_16,td_strs_mat_17,td_strs_mat_18
      external td_strs_mat_19,td_strs_mat_20
c
c version
c $Id: td_strs_mat_ext.inc,v 1.1 2004/06/24 21:36:28 willic3 Exp $
c
c Generated automatically by Fortran77Mill on Wed May 21 21:38:38 2003
c
c End of file 
