c -*- Fortran -*-
c
c~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c
c                             Charles A. Williams
c                       Rensselaer Polytechnic Institute
c                        (C) 2003  All Rights Reserved
c
c <LicenseText>
c
c~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c
c...  implicit.inc:  A header that sets 'implicit none' for all
c     routines in which it is included.  This could be done separately
c     in each routine, but it is remotely possible that some typing
c     will be required on some platforms.  This will make it easy to
c     perform that task globally.  This file should be included in the
c     first line of every program or subroutine.
c
      implicit none
c
c version
c $Id: implicit.inc,v 1.1 2004/04/14 21:18:30 willic3 Exp $
c
c Generated automatically by Fortran77Mill on Wed May 21 21:38:38 2003
c
c End of file 
