c -*- Fortran -*-
c
c~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c
c                             Charles A. Williams
c                       Rensselaer Polytechnic Institute
c                        (C) 2003  All Rights Reserved
c
c <LicenseText>
c
c~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c
c...  nconsts_par.inc:  A set of commonly-used integer constants.
c
      integer izero,ione,itwo,ithree,ifour,ifive,isix,iseven,ieight
      integer inine
c
      parameter(izero   = 0,
     &          ione    = 1,
     &          itwo    = 2,
     &          ithree  = 3,
     &          ifour   = 4,
     &          ifive   = 5,
     &          isix    = 6,
     &          iseven  = 7,
     &          ieight  = 8,
     &          inine   = 9)
c
c version
c $Id: nconsts.inc,v 1.1 2004/04/14 21:18:30 willic3 Exp $
c
c Generated automatically by Fortran77Mill on Wed May 21 21:38:38 2003
c
c End of file 
