#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#
#  Makefile to test subroutines.  This makefile can be used to test
#  for undefined variables and to see what intrinsics are used.
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PROJ_F77_INCLUDES= -I./includes

PROJ_CPP_INCLUDES= -I$(PETSC_DIR)/include -I$(PETSC_DIR)/bmake/$(PETSC_ARCH) -I$(MPI_INCDIR) -I$(PETSC_DIR)

#FFLAGC= -fno-silent -fno-ugly -fno-f77 -ff90 -fpedantic -Wall -fbackslash -Wsurprising -W $(PROJ_F77_INCLUDES) $(PROJ_CPP_INCLUDES)

FFLAGC= -Wall -fbackslash -W -DFORTRAN_POSITION_APPEND -DFORTRAN_STREAM_IO $(PROJ_F77_INCLUDES) $(PROJ_CPP_INCLUDES)

CFLAGC= 

# opt   = -O3 -funroll-loops

opt   = -g

load  = 

FCOMPL= mpif90

CCOMPL= mpicc

.SUFFIXES: .F .f .c .s .o .fil

.F.f:
	$(FCOMPL) $(FFLAGC) -F $<

.F.o:
	$(FCOMPL) -c $(FFLAGC) $(opt) $<

.f.o:
	$(FCOMPL) -c $(FFLAGC) $(opt) $<

.f.fil:
	$(FCOMPL) -il $(FFLAGC) $<

.s.o:
	as $<

.c.o:
	$(CCOMPL) -c $(CFLAGC) $(opt) $<

clean:
	/bin/rm -f *.o
