// -*- C++ -*-
//
// ======================================================================
//
// Brad T. Aagaard, U.S. Geological Survey
// Charles A. Williams, GNS Science
// Matthew G. Knepley, University of Chicago
//
// This code was developed as part of the Computational Infrastructure
// for Geodynamics (http://geodynamics.org).
//
// Copyright (c) 2010-2011 University of California, Davis
//
// See COPYING for license information.
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application druckerpragerplanestraintimedep.

#include "DruckerPragerPlaneStrainTimeDepData.hh"

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_dimension = 2;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numLocs = 2;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numProperties = 6;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numStateVars = 2;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numDBProperties = 6;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numDBStateVars = 5;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numPropsQuadPt = 6;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numVarsQuadPt = 5;

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_lengthScale =   1.00000000e+03;

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_timeScale =   1.00000000e+00;

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_pressureScale =   2.25000000e+10;

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_densityScale =   1.00000000e+03;

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_dtStableImplicit =   1.00000000e+30;

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numPropertyValues[] = {
1,
1,
1,
1,
1,
1,
};

const int pylith::materials::DruckerPragerPlaneStrainTimeDepData::_numStateVarValues[] = {
1,
4,
};

const char* pylith::materials::DruckerPragerPlaneStrainTimeDepData::_dbPropertyValues[] = {
"density",
"vs",
"vp",
"friction-angle",
"cohesion",
"dilatation-angle",
};

const char* pylith::materials::DruckerPragerPlaneStrainTimeDepData::_dbStateVarValues[] = {
"stress-zz-initial",
"plastic-strain-xx",
"plastic-strain-yy",
"plastic-strain-zz",
"plastic-strain-xy",
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_dbProperties[] = {
  2.50000000e+03,
  3.00000000e+03,
  5.19615242e+03,
  5.23598776e-01,
  3.00000000e+05,
  3.49065850e-01,
  2.00000000e+03,
  1.20000000e+03,
  2.07846097e+03,
  4.36332313e-01,
  1.00000000e+04,
  4.36332313e-01,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_dbStateVars[] = {
  1.07500000e+04,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  2.57500000e+04,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_properties[] = {
  2.50000000e+03,
  2.25000000e+10,
  2.25000000e+10,
  2.30940108e-01,
  3.60000000e+05,
  1.48583084e-01,
  2.00000000e+03,
  2.88000000e+09,
  2.88000000e+09,
  1.89338478e-01,
  1.21811303e+04,
  1.89338478e-01,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_stateVars[] = {
  1.07500000e+04,
  4.10000000e-05,
  4.20000000e-05,
  4.40000000e-05,
  4.50000000e-05,
  2.57500000e+04,
  1.10000000e-05,
  1.20000000e-05,
  1.40000000e-05,
  1.50000000e-05,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_propertiesNondim[] = {
  2.50000000e+00,
  1.00000000e+00,
  1.00000000e+00,
  2.30940108e-01,
  1.60000000e-05,
  1.48583084e-01,
  2.00000000e+00,
  1.28000000e-01,
  1.28000000e-01,
  1.89338478e-01,
  5.41383567e-07,
  1.89338478e-01,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_stateVarsNondim[] = {
  4.77777778e-07,
  4.77777778e-07,
  4.77777778e-07,
  4.77777778e-07,
  4.77777778e-07,
  1.14444444e-06,
  1.14444444e-06,
  1.14444444e-06,
  1.14444444e-06,
  1.14444444e-06,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_density[] = {
  2.50000000e+03,
  2.00000000e+03,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_strain[] = {
  1.10000000e-04,
  1.20000000e-04,
  1.40000000e-04,
  4.10000000e-04,
  4.20000000e-04,
  4.40000000e-04,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_stress[] = {
 -4.95807185e+05,
 -3.82197636e+05,
  7.08863124e+05,
  5.51473672e+05,
  5.45142209e+05,
 -2.85351554e+05,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_elasticConsts[] = {
  2.44487161e+10,
  1.17789183e+10,
 -1.66473214e+10,
  1.09997245e+10,
  2.10335485e+10,
 -1.62468306e+10,
 -1.31854142e+10,
 -1.29851687e+10,
  1.38346134e+10,
  1.73722726e+09,
  2.48498883e+09,
 -2.42123101e+09,
  2.48498825e+09,
  1.68402528e+09,
 -2.37432763e+09,
 -1.21061568e+09,
 -1.18716349e+09,
  1.33926043e+09,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_initialStress[] = {
  2.10000000e+04,
  2.20000000e+04,
  2.40000000e+04,
  5.10000000e+04,
  5.20000000e+04,
  5.40000000e+04,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_initialStrain[] = {
  3.60000000e-05,
  3.50000000e-05,
  3.30000000e-05,
  6.10000000e-05,
  6.20000000e-05,
  6.60000000e-05,
};

const PylithScalar pylith::materials::DruckerPragerPlaneStrainTimeDepData::_stateVarsUpdated[] = {
  1.07500000e+04,
  7.52490579e-05,
  8.37466235e-05,
  2.04754109e-05,
  9.17808195e-05,
  2.57500000e+04,
  3.24452570e-04,
  3.34725393e-04,
 -7.68586819e-05,
  4.32915200e-04,
};

pylith::materials::DruckerPragerPlaneStrainTimeDepData::DruckerPragerPlaneStrainTimeDepData(void)
{ // constructor
  dimension = _dimension;
  numLocs = _numLocs;
  numProperties = _numProperties;
  numStateVars = _numStateVars;
  numDBProperties = _numDBProperties;
  numDBStateVars = _numDBStateVars;
  numPropsQuadPt = _numPropsQuadPt;
  numVarsQuadPt = _numVarsQuadPt;
  lengthScale = _lengthScale;
  timeScale = _timeScale;
  pressureScale = _pressureScale;
  densityScale = _densityScale;
  dtStableImplicit = _dtStableImplicit;
  numPropertyValues = const_cast<int*>(_numPropertyValues);
  numStateVarValues = const_cast<int*>(_numStateVarValues);
  dbPropertyValues = const_cast<char**>(_dbPropertyValues);
  dbStateVarValues = const_cast<char**>(_dbStateVarValues);
  dbProperties = const_cast<PylithScalar*>(_dbProperties);
  dbStateVars = const_cast<PylithScalar*>(_dbStateVars);
  properties = const_cast<PylithScalar*>(_properties);
  stateVars = const_cast<PylithScalar*>(_stateVars);
  propertiesNondim = const_cast<PylithScalar*>(_propertiesNondim);
  stateVarsNondim = const_cast<PylithScalar*>(_stateVarsNondim);
  density = const_cast<PylithScalar*>(_density);
  strain = const_cast<PylithScalar*>(_strain);
  stress = const_cast<PylithScalar*>(_stress);
  elasticConsts = const_cast<PylithScalar*>(_elasticConsts);
  initialStress = const_cast<PylithScalar*>(_initialStress);
  initialStrain = const_cast<PylithScalar*>(_initialStrain);
  stateVarsUpdated = const_cast<PylithScalar*>(_stateVarsUpdated);
} // constructor

pylith::materials::DruckerPragerPlaneStrainTimeDepData::~DruckerPragerPlaneStrainTimeDepData(void)
{}


// End of file
