// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application elasticplanestrain.

#if !defined(pylith_materials_elasticplanestressdata_hh)
#define pylith_materials_elasticplanestressdata_hh

#include "ElasticMaterialData.hh"

namespace pylith {
  namespace materials {
     class ElasticPlaneStressData;
  } // pylith
} // materials

class pylith::materials::ElasticPlaneStressData : public ElasticMaterialData
{

public: 

  /// Constructor
  ElasticPlaneStressData(void);

  /// Destructor
  ~ElasticPlaneStressData(void);

private:

  static const int _dimension;

  static const int _numDBValues;

  static const int _numParameters;

  static const int _numLocs;

  static const char* _dbValues[];

  static const char* _parameterNames[];

  static const double _dbData[];

  static const double _parameterData[];

  static const double _density[];

  static const double _strain[];

  static const double _stress[];

  static const double _elasticConsts[];

};

#endif // pylith_materials_elasticplanestressdata_hh

// End of file
