// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application elasticstrain1d.

#include "ElasticStrain1DData.hh"

const int pylith::materials::ElasticStrain1DData::_dimension = 1;

const int pylith::materials::ElasticStrain1DData::_numDBValues = 3;

const int pylith::materials::ElasticStrain1DData::_numInitialStateValues = 1;

const int pylith::materials::ElasticStrain1DData::_numParameters = 3;

const int pylith::materials::ElasticStrain1DData::_numParamsQuadPt = 3;

const int pylith::materials::ElasticStrain1DData::_numLocs = 2;

const double pylith::materials::ElasticStrain1DData::_dtStableImplicit =   1.00000000e+30;

const int pylith::materials::ElasticStrain1DData::_numParamValues[] = {
1,
1,
1,
};

const char* pylith::materials::ElasticStrain1DData::_dbValues[] = {
"density",
"vs",
"vp",
};

const char* pylith::materials::ElasticStrain1DData::_initialStateDBValues[] = {
"stress_xx",
};

const double pylith::materials::ElasticStrain1DData::_dbData[] = {
  2.50000000e+03,
  3.00000000e+03,
  5.19615242e+03,
  2.00000000e+03,
  1.20000000e+03,
  2.07846097e+03,
};

const double pylith::materials::ElasticStrain1DData::_initialStateDBData[] = {
  1.20000000e+04,
  2.10000000e+04,
};

const double pylith::materials::ElasticStrain1DData::_parameterData[] = {
  2.50000000e+03,
  2.25000000e+10,
  2.25000000e+10,
  2.00000000e+03,
  2.88000000e+09,
  2.88000000e+09,
};

const double pylith::materials::ElasticStrain1DData::_initialState[] = {
  1.20000000e+04,
  2.10000000e+04,
};

const double pylith::materials::ElasticStrain1DData::_density[] = {
  2.50000000e+03,
  2.00000000e+03,
};

const double pylith::materials::ElasticStrain1DData::_strain[] = {
  1.10000000e-04,
  1.20000000e-04,
};

const double pylith::materials::ElasticStrain1DData::_stress[] = {
  7.43700000e+06,
  1.05780000e+06,
};

const double pylith::materials::ElasticStrain1DData::_elasticConsts[] = {
  6.75000000e+10,
  8.64000000e+09,
};

pylith::materials::ElasticStrain1DData::ElasticStrain1DData(void)
{ // constructor
  dimension = _dimension;
  numDBValues = _numDBValues;
  numInitialStateValues = _numInitialStateValues;
  numParameters = _numParameters;
  numParamsQuadPt = _numParamsQuadPt;
  numLocs = _numLocs;
  dtStableImplicit = _dtStableImplicit;
  numParamValues = const_cast<int*>(_numParamValues);
  dbValues = const_cast<char**>(_dbValues);
  initialStateDBValues = const_cast<char**>(_initialStateDBValues);
  dbData = const_cast<double*>(_dbData);
  initialStateDBData = const_cast<double*>(_initialStateDBData);
  parameterData = const_cast<double*>(_parameterData);
  initialState = const_cast<double*>(_initialState);
  density = const_cast<double*>(_density);
  strain = const_cast<double*>(_strain);
  stress = const_cast<double*>(_stress);
  elasticConsts = const_cast<double*>(_elasticConsts);
} // constructor

pylith::materials::ElasticStrain1DData::~ElasticStrain1DData(void)
{}


// End of file
