// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application elasticstress1d.

#include "ElasticStress1DData.hh"

const int pylith::materials::ElasticStress1DData::_dimension = 1;

const int pylith::materials::ElasticStress1DData::_numDBValues = 3;

const int pylith::materials::ElasticStress1DData::_numParameters = 3;

const int pylith::materials::ElasticStress1DData::_numLocs = 2;

const int pylith::materials::ElasticStress1DData::_numParamValues[] = {
1,
1,
1,
};

const char* pylith::materials::ElasticStress1DData::_dbValues[] = {
"density",
"vs",
"vp",
};

const char* pylith::materials::ElasticStress1DData::_parameterNames[] = {
"density",
"mu",
"lambda",
};

const double pylith::materials::ElasticStress1DData::_dbData[] = {
  2.50000000e+03,
  3.00000000e+03,
  5.19615242e+03,
  2.00000000e+03,
  1.20000000e+03,
  2.07846097e+03,
};

const double pylith::materials::ElasticStress1DData::_parameterData[] = {
  2.50000000e+03,
  2.25000000e+10,
  2.25000000e+10,
  2.00000000e+03,
  2.88000000e+09,
  2.88000000e+09,
};

const double pylith::materials::ElasticStress1DData::_density[] = {
  2.50000000e+03,
  2.00000000e+03,
};

const double pylith::materials::ElasticStress1DData::_strain[] = {
  1.10000000e-04,
  1.20000000e-04,
};

const double pylith::materials::ElasticStress1DData::_stress[] = {
  6.18750000e+06,
  8.64000000e+05,
};

const double pylith::materials::ElasticStress1DData::_elasticConsts[] = {
  5.62500000e+10,
  7.20000000e+09,
};

pylith::materials::ElasticStress1DData::ElasticStress1DData(void)
{ // constructor
  dimension = _dimension;
  numDBValues = _numDBValues;
  numParameters = _numParameters;
  numLocs = _numLocs;
  numParamValues = const_cast<int*>(_numParamValues);
  dbValues = const_cast<char**>(_dbValues);
  parameterNames = const_cast<char**>(_parameterNames);
  dbData = const_cast<double*>(_dbData);
  parameterData = const_cast<double*>(_parameterData);
  density = const_cast<double*>(_density);
  strain = const_cast<double*>(_strain);
  stress = const_cast<double*>(_stress);
  elasticConsts = const_cast<double*>(_elasticConsts);
} // constructor

pylith::materials::ElasticStress1DData::~ElasticStress1DData(void)
{}


// End of file
