// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application elasticstrain1d.

#include "ElasticStrain1DData.hh"

const int pylith::materials::ElasticStrain1DData::_dimension = 1;

const int pylith::materials::ElasticStrain1DData::_numDBValues = 2;

const int pylith::materials::ElasticStrain1DData::_numParameters = 2;

const int pylith::materials::ElasticStrain1DData::_numLocs = 2;

const char* pylith::materials::ElasticStrain1DData::_dbValues[] = {
"density",
"vp",
};

const char* pylith::materials::ElasticStrain1DData::_parameterNames[] = {
"density",
"lambda2mu",
};

const double pylith::materials::ElasticStrain1DData::_dbData[] = {
  2.50000000e+03,
  5.00000000e+03,
  2.00000000e+03,
  3.00000000e+03,
};

const double pylith::materials::ElasticStrain1DData::_parameterData[] = {
  2.50000000e+03,
  6.25000000e+10,
  2.80000000e+03,
  1.80000000e+10,
};

const double pylith::materials::ElasticStrain1DData::_density[] = {
  2.50000000e+03,
  2.00000000e+03,
};

const double pylith::materials::ElasticStrain1DData::_strain[] = {
  1.10000000e-04,
  1.20000000e-04,
};

const double pylith::materials::ElasticStrain1DData::_stress[] = {
  6.87500000e+06,
  2.16000000e+06,
};

const double pylith::materials::ElasticStrain1DData::_elasticConsts[] = {
  6.25000000e+10,
  1.80000000e+10,
};

pylith::materials::ElasticStrain1DData::ElasticStrain1DData(void)
{ // constructor
  dimension = _dimension;
  numDBValues = _numDBValues;
  numParameters = _numParameters;
  numLocs = _numLocs;
  dbValues = const_cast<char**>(_dbValues);
  parameterNames = const_cast<char**>(_parameterNames);
  dbData = const_cast<double*>(_dbData);
  parameterData = const_cast<double*>(_parameterData);
  density = const_cast<double*>(_density);
  strain = const_cast<double*>(_strain);
  stress = const_cast<double*>(_stress);
  elasticConsts = const_cast<double*>(_elasticConsts);
} // constructor

pylith::materials::ElasticStrain1DData::~ElasticStrain1DData(void)
{}


// End of file
