// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application genmaxwellisotropic3dtimedep.

#include "GenMaxwellIsotropic3DTimeDepData.hh"

const int pylith::materials::GenMaxwellIsotropic3DTimeDepData::_dimension = 3;

const int pylith::materials::GenMaxwellIsotropic3DTimeDepData::_numDBValues = 9;

const int pylith::materials::GenMaxwellIsotropic3DTimeDepData::_numInitialStateValues = 6;

const int pylith::materials::GenMaxwellIsotropic3DTimeDepData::_numParameters = 7;

const int pylith::materials::GenMaxwellIsotropic3DTimeDepData::_numParamsQuadPt = 33;

const int pylith::materials::GenMaxwellIsotropic3DTimeDepData::_numLocs = 2;

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_dtStableImplicit =   4.44444444e+06;

const int pylith::materials::GenMaxwellIsotropic3DTimeDepData::_numParamValues[] = {
1,
1,
1,
3,
3,
6,
18,
};

const char* pylith::materials::GenMaxwellIsotropic3DTimeDepData::_dbValues[] = {
"density",
"vs",
"vp",
"shear_ratio_1",
"shear_ratio_2",
"shear_ratio_3",
"viscosity_1",
"viscosity_2",
"viscosity_3",
};

const char* pylith::materials::GenMaxwellIsotropic3DTimeDepData::_initialStateDBValues[] = {
"stress_xx",
"stress_yy",
"stress_zz",
"stress_xy",
"stress_yz",
"stress_xy",
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_dbData[] = {
  2.50000000e+03,
  3.00000000e+03,
  5.19615242e+03,
  5.00000000e-01,
  1.00000000e-01,
  2.00000000e-01,
  1.00000000e+18,
  1.00000000e+17,
  1.00000000e+19,
  2.00000000e+03,
  1.20000000e+03,
  2.07846097e+03,
  2.00000000e-01,
  2.00000000e-01,
  2.00000000e-01,
  1.00000000e+18,
  1.00000000e+19,
  1.00000000e+20,
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_initialStateDBData[] = {
  1.20000000e+04,
  2.30000000e+04,
  3.40000000e+04,
  4.50000000e+04,
  5.60000000e+04,
  6.70000000e+04,
  2.10000000e+04,
  3.20000000e+04,
  4.30000000e+04,
  5.40000000e+04,
  6.50000000e+04,
  7.60000000e+04,
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_parameterData[] = {
  2.50000000e+03,
  2.25000000e+10,
  2.25000000e+10,
  5.00000000e-01,
  1.00000000e-01,
  2.00000000e-01,
  8.88888889e+07,
  4.44444444e+07,
  2.22222222e+09,
  1.10000000e-04,
  2.20000000e-04,
  3.30000000e-04,
  4.40000000e-04,
  5.50000000e-04,
  6.60000000e-04,
 -1.10000000e-04,
  0.00000000e+00,
  1.10000000e-04,
  4.40000000e-04,
  5.50000000e-04,
  6.60000000e-04,
 -1.10000000e-04,
  0.00000000e+00,
  1.10000000e-04,
  4.40000000e-04,
  5.50000000e-04,
  6.60000000e-04,
 -1.10000000e-04,
  0.00000000e+00,
  1.10000000e-04,
  4.40000000e-04,
  5.50000000e-04,
  6.60000000e-04,
  2.00000000e+03,
  2.88000000e+09,
  2.88000000e+09,
  2.00000000e-01,
  2.00000000e-01,
  2.00000000e-01,
  1.73611111e+09,
  1.73611111e+10,
  1.73611111e+11,
  1.20000000e-04,
  2.30000000e-04,
  3.40000000e-04,
  4.50000000e-04,
  5.60000000e-04,
  6.70000000e-04,
 -1.10000000e-04,
 -2.71050543e-20,
  1.10000000e-04,
  4.50000000e-04,
  5.60000000e-04,
  6.70000000e-04,
 -1.10000000e-04,
 -2.71050543e-20,
  1.10000000e-04,
  4.50000000e-04,
  5.60000000e-04,
  6.70000000e-04,
 -1.10000000e-04,
 -2.71050543e-20,
  1.10000000e-04,
  4.50000000e-04,
  5.60000000e-04,
  6.70000000e-04,
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_initialState[] = {
  1.20000000e+04,
  2.30000000e+04,
  3.40000000e+04,
  4.50000000e+04,
  5.60000000e+04,
  6.70000000e+04,
  2.10000000e+04,
  3.20000000e+04,
  4.30000000e+04,
  5.40000000e+04,
  6.50000000e+04,
  7.60000000e+04,
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_density[] = {
  2.50000000e+03,
  2.00000000e+03,
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_strain[] = {
  1.10000000e-04,
  2.20000000e-04,
  3.30000000e-04,
  4.40000000e-04,
  5.50000000e-04,
  6.60000000e-04,
  1.20000000e-04,
  2.30000000e-04,
  3.40000000e-04,
  4.50000000e-04,
  5.60000000e-04,
  6.70000000e-04,
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_stress[] = {
  1.98198741e+07,
  2.47730000e+07,
  2.97261259e+07,
  1.98135037e+07,
  2.47666296e+07,
  2.97197555e+07,
  2.69941620e+06,
  3.34400000e+06,
  3.98858380e+06,
  2.64593371e+06,
  3.29051751e+06,
  3.93510131e+06,
};

const double pylith::materials::GenMaxwellIsotropic3DTimeDepData::_elasticConsts[] = {
  6.74761278e+10,
  2.25119361e+10,
  2.25119361e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  6.74761278e+10,
  2.25119361e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  6.74761278e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  4.49641917e+10,
  0.00000000e+00,
  0.00000000e+00,
  4.49641917e+10,
  0.00000000e+00,
  4.49641917e+10,
  8.63995090e+09,
  2.88002455e+09,
  2.88002455e+09,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  8.63995090e+09,
  2.88002455e+09,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  8.63995090e+09,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  5.75992635e+09,
  0.00000000e+00,
  0.00000000e+00,
  5.75992635e+09,
  0.00000000e+00,
  5.75992635e+09,
};

pylith::materials::GenMaxwellIsotropic3DTimeDepData::GenMaxwellIsotropic3DTimeDepData(void)
{ // constructor
  dimension = _dimension;
  numDBValues = _numDBValues;
  numInitialStateValues = _numInitialStateValues;
  numParameters = _numParameters;
  numParamsQuadPt = _numParamsQuadPt;
  numLocs = _numLocs;
  dtStableImplicit = _dtStableImplicit;
  numParamValues = const_cast<int*>(_numParamValues);
  dbValues = const_cast<char**>(_dbValues);
  initialStateDBValues = const_cast<char**>(_initialStateDBValues);
  dbData = const_cast<double*>(_dbData);
  initialStateDBData = const_cast<double*>(_initialStateDBData);
  parameterData = const_cast<double*>(_parameterData);
  initialState = const_cast<double*>(_initialState);
  density = const_cast<double*>(_density);
  strain = const_cast<double*>(_strain);
  stress = const_cast<double*>(_stress);
  elasticConsts = const_cast<double*>(_elasticConsts);
} // constructor

pylith::materials::GenMaxwellIsotropic3DTimeDepData::~GenMaxwellIsotropic3DTimeDepData(void)
{}


// End of file
