// -*- C++ -*-
//
// ======================================================================
//
// Brad T. Aagaard, U.S. Geological Survey
// Charles A. Williams, GNS Science
// Matthew G. Knepley, University of Chicago
//
// This code was developed as part of the Computational Infrastructure
// for Geodynamics (http://geodynamics.org).
//
// Copyright (c) 2010-2015 University of California, Davis
//
// See COPYING for license information.
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application IsotropicLinearElasticityPlaneStrain.py.

#include "IsotropicLinearElasticityPlaneStrainData_Tri3.hh"

extern "C" {
#include "pylith/fekernels/elasticity.h"
}

const char* pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_filenameMesh = "data/tri3.mesh";

const char* pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_label = "IsotropicLinearElascitity";

const int pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_id = 0;

const int pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_dimension = 2;

const bool pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_useInertia = false;

const bool pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_useBodyForce = false;

const int pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_numSolnFields = 1;

const PylithScalar pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_lengthScale =   1.00000000e+03;

const PylithScalar pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_timeScale =   2.00000000e+00;

const PylithScalar pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_densityScale =   9.00000000e+04;

const PylithScalar pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_pressureScale =   2.25000000e+10;

const PetscPointFunc pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_residualKernels[] = {
  NULL,
  pylith_fekernels_f1_IsotropicLinearElasticityPlaneStrain,
};

const PetscPointJac pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::_jacobianKernels[] = {
  NULL,
  NULL,
  NULL,
  pylith_fekernels_g3_uu_IsotropicLinearElasticityPlaneStrain,
};

pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::IsotropicLinearElasticityPlaneStrainData_Tri3(void)
{ // constructor
  filenameMesh = const_cast<char*>(_filenameMesh);
  label = const_cast<char*>(_label);
  id = _id;
  dimension = _dimension;
  useInertia = _useInertia;
  useBodyForce = _useBodyForce;
  numSolnFields = _numSolnFields;
  lengthScale = _lengthScale;
  timeScale = _timeScale;
  densityScale = _densityScale;
  pressureScale = _pressureScale;
  residualKernels = const_cast<PetscPointFunc*>(_residualKernels);
  jacobianKernels = const_cast<PetscPointJac*>(_jacobianKernels);
} // constructor

pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3::~IsotropicLinearElasticityPlaneStrainData_Tri3(void)
{}


// End of file
