// -*- C++ -*-
//
// ======================================================================
//
// Brad T. Aagaard, U.S. Geological Survey
// Charles A. Williams, GNS Science
// Matthew G. Knepley, University of Chicago
//
// This code was developed as part of the Computational Infrastructure
// for Geodynamics (http://geodynamics.org).
//
// Copyright (c) 2010-2015 University of California, Davis
//
// See COPYING for license information.
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application IsotropicLinearElasticityPlaneStrain.py.

#if !defined(pylith_materials_isotropiclinearelasticityplanestraindata_tri3_hh)
#define pylith_materials_isotropiclinearelasticityplanestraindata_tri3_hh

#include "IsotropicLinearElasticityPlaneStrainData.hh"

namespace pylith {
  namespace materials {
    class IsotropicLinearElasticityPlaneStrainData_Tri3;
  } // pylith
} // materials

class pylith::materials::IsotropicLinearElasticityPlaneStrainData_Tri3 : public IsotropicLinearElasticityPlaneStrainData
{

public: 

  /// Constructor
  IsotropicLinearElasticityPlaneStrainData_Tri3(void);

  /// Destructor
  ~IsotropicLinearElasticityPlaneStrainData_Tri3(void);

private:

  static const char* _filenameMesh;

  static const char* _label;

  static const int _id;

  static const int _dimension;

  static const bool _useInertia;

  static const bool _useBodyForce;

  static const int _numSolnFields;

  static const PylithScalar _lengthScale;

  static const PylithScalar _timeScale;

  static const PylithScalar _densityScale;

  static const PylithScalar _pressureScale;

  static const PetscPointFunc _residualKernels[];

  static const PetscPointJac _jacobianKernels[];

};

#endif // pylith_materials_isotropiclinearelasticityplanestraindata_tri3_hh

// End of file
