// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application maxwellisotropic3delastic.

#include "MaxwellIsotropic3DElasticData.hh"

const int pylith::materials::MaxwellIsotropic3DElasticData::_dimension = 3;

const int pylith::materials::MaxwellIsotropic3DElasticData::_numDBValues = 4;

const int pylith::materials::MaxwellIsotropic3DElasticData::_numInitialStateValues = 6;

const int pylith::materials::MaxwellIsotropic3DElasticData::_numParameters = 6;

const int pylith::materials::MaxwellIsotropic3DElasticData::_numParamsQuadPt = 16;

const int pylith::materials::MaxwellIsotropic3DElasticData::_numLocs = 2;

const double pylith::materials::MaxwellIsotropic3DElasticData::_dtStableImplicit =   1.00000000e+30;

const int pylith::materials::MaxwellIsotropic3DElasticData::_numParamValues[] = {
1,
1,
1,
1,
6,
6,
};

const char* pylith::materials::MaxwellIsotropic3DElasticData::_dbValues[] = {
"density",
"vs",
"vp",
"viscosity",
};

const char* pylith::materials::MaxwellIsotropic3DElasticData::_initialStateDBValues[] = {
"stress_xx",
"stress_yy",
"stress_zz",
"stress_xy",
"stress_yz",
"stress_xy",
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_dbData[] = {
  2.50000000e+03,
  3.00000000e+03,
  5.19615242e+03,
  1.00000000e+18,
  2.00000000e+03,
  1.20000000e+03,
  2.07846097e+03,
  1.00000000e+18,
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_initialStateDBData[] = {
  1.20000000e+04,
  2.30000000e+04,
  3.40000000e+04,
  4.50000000e+04,
  5.60000000e+04,
  6.70000000e+04,
  2.10000000e+04,
  3.20000000e+04,
  4.30000000e+04,
  5.40000000e+04,
  6.50000000e+04,
  7.60000000e+04,
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_parameterData[] = {
  2.50000000e+03,
  2.25000000e+10,
  2.25000000e+10,
  4.44444444e+07,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  2.00000000e+03,
  2.88000000e+09,
  2.88000000e+09,
  3.47222222e+08,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_initialState[] = {
  1.20000000e+04,
  2.30000000e+04,
  3.40000000e+04,
  4.50000000e+04,
  5.60000000e+04,
  6.70000000e+04,
  2.10000000e+04,
  3.20000000e+04,
  4.30000000e+04,
  5.40000000e+04,
  6.50000000e+04,
  7.60000000e+04,
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_density[] = {
  2.50000000e+03,
  2.00000000e+03,
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_strain[] = {
  1.10000000e-04,
  2.20000000e-04,
  3.30000000e-04,
  4.40000000e-04,
  5.50000000e-04,
  6.60000000e-04,
  1.20000000e-04,
  2.30000000e-04,
  3.40000000e-04,
  4.50000000e-04,
  5.60000000e-04,
  6.70000000e-04,
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_stress[] = {
  1.98120000e+07,
  2.47730000e+07,
  2.97340000e+07,
  1.98450000e+07,
  2.48060000e+07,
  2.97670000e+07,
  2.69940000e+06,
  3.34400000e+06,
  3.98860000e+06,
  2.64600000e+06,
  3.29060000e+06,
  3.93520000e+06,
};

const double pylith::materials::MaxwellIsotropic3DElasticData::_elasticConsts[] = {
  6.75000000e+10,
  2.25000000e+10,
  2.25000000e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  6.75000000e+10,
  2.25000000e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  6.75000000e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  4.50000000e+10,
  0.00000000e+00,
  0.00000000e+00,
  4.50000000e+10,
  0.00000000e+00,
  4.50000000e+10,
  8.64000000e+09,
  2.88000000e+09,
  2.88000000e+09,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  8.64000000e+09,
  2.88000000e+09,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  8.64000000e+09,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  5.76000000e+09,
  0.00000000e+00,
  0.00000000e+00,
  5.76000000e+09,
  0.00000000e+00,
  5.76000000e+09,
};

pylith::materials::MaxwellIsotropic3DElasticData::MaxwellIsotropic3DElasticData(void)
{ // constructor
  dimension = _dimension;
  numDBValues = _numDBValues;
  numInitialStateValues = _numInitialStateValues;
  numParameters = _numParameters;
  numParamsQuadPt = _numParamsQuadPt;
  numLocs = _numLocs;
  dtStableImplicit = _dtStableImplicit;
  numParamValues = const_cast<int*>(_numParamValues);
  dbValues = const_cast<char**>(_dbValues);
  initialStateDBValues = const_cast<char**>(_initialStateDBValues);
  dbData = const_cast<double*>(_dbData);
  initialStateDBData = const_cast<double*>(_initialStateDBData);
  parameterData = const_cast<double*>(_parameterData);
  initialState = const_cast<double*>(_initialState);
  density = const_cast<double*>(_density);
  strain = const_cast<double*>(_strain);
  stress = const_cast<double*>(_stress);
  elasticConsts = const_cast<double*>(_elasticConsts);
} // constructor

pylith::materials::MaxwellIsotropic3DElasticData::~MaxwellIsotropic3DElasticData(void)
{}


// End of file
