// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application powerlaw3dtimedep.

#include "PowerLaw3DTimeDepData.hh"

const int pylith::materials::PowerLaw3DTimeDepData::_dimension = 3;

const int pylith::materials::PowerLaw3DTimeDepData::_numLocs = 2;

const int pylith::materials::PowerLaw3DTimeDepData::_numProperties = 5;

const int pylith::materials::PowerLaw3DTimeDepData::_numStateVars = 2;

const int pylith::materials::PowerLaw3DTimeDepData::_numDBProperties = 5;

const int pylith::materials::PowerLaw3DTimeDepData::_numDBStateVars = 12;

const int pylith::materials::PowerLaw3DTimeDepData::_numPropsQuadPt = 5;

const int pylith::materials::PowerLaw3DTimeDepData::_numVarsQuadPt = 12;

const double pylith::materials::PowerLaw3DTimeDepData::_lengthScale =   1.00000000e+03;

const double pylith::materials::PowerLaw3DTimeDepData::_timeScale =   1.00000000e+00;

const double pylith::materials::PowerLaw3DTimeDepData::_pressureScale =   2.25000000e+10;

const double pylith::materials::PowerLaw3DTimeDepData::_densityScale =   1.00000000e+03;

const double pylith::materials::PowerLaw3DTimeDepData::_dtStableImplicit =   4.44444444e+06;

const int pylith::materials::PowerLaw3DTimeDepData::_numPropertyValues[] = {
1,
1,
1,
1,
1,
};

const int pylith::materials::PowerLaw3DTimeDepData::_numStateVarValues[] = {
6,
6,
};

const char* pylith::materials::PowerLaw3DTimeDepData::_dbPropertyValues[] = {
"density",
"vs",
"vp",
"viscosity_coeff",
"power_law_exponent",
};

const char* pylith::materials::PowerLaw3DTimeDepData::_dbStateVarValues[] = {
"viscous-strain-xx",
"viscous-strain-yy",
"viscous-strain-zz",
"viscous-strain-xy",
"viscous-strain-yz",
"viscous-strain-xz",
"stress-xx",
"stress-yy",
"stress-zz",
"stress-xy",
"stress-yz",
"stress-xz",
};

const double pylith::materials::PowerLaw3DTimeDepData::_dbProperties[] = {
  2.50000000e+03,
  3.00000000e+03,
  5.19615242e+03,
  1.00000000e+18,
  1.00000000e+00,
  2.00000000e+03,
  1.20000000e+03,
  2.07846097e+03,
  1.00000000e+10,
  3.00000000e+00,
};

const double pylith::materials::PowerLaw3DTimeDepData::_dbStateVars[] = {
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
};

const double pylith::materials::PowerLaw3DTimeDepData::_properties[] = {
  2.50000000e+03,
  2.25000000e+10,
  2.25000000e+10,
  1.00000000e+18,
  1.00000000e+00,
  2.00000000e+03,
  2.88000000e+09,
  2.88000000e+09,
  1.00000000e+10,
  3.00000000e+00,
};

const double pylith::materials::PowerLaw3DTimeDepData::_stateVars[] = {
  4.10000000e-05,
  4.20000000e-05,
  4.30000000e-05,
  4.40000000e-05,
  4.50000000e-05,
  4.60000000e-05,
  3.10000000e+04,
  3.20000000e+04,
  3.30000000e+04,
  3.40000000e+04,
  3.50000000e+04,
  3.60000000e+04,
  1.10000000e-05,
  1.20000000e-05,
  1.30000000e-05,
  1.40000000e-05,
  1.50000000e-05,
  1.60000000e-05,
  5.10000000e+04,
  5.20000000e+04,
  5.30000000e+04,
  5.40000000e+04,
  5.50000000e+04,
  5.60000000e+04,
};

const double pylith::materials::PowerLaw3DTimeDepData::_propertiesNondim[] = {
  2.50000000e+00,
  1.00000000e+00,
  1.00000000e+00,
  4.44444444e+07,
  1.00000000e+00,
  2.00000000e+00,
  1.28000000e-01,
  1.28000000e-01,
  3.54219523e+06,
  3.00000000e+00,
};

const double pylith::materials::PowerLaw3DTimeDepData::_stateVarsNondim[] = {
  4.10000000e-05,
  4.20000000e-05,
  4.30000000e-05,
  4.40000000e-05,
  4.50000000e-05,
  4.60000000e-05,
  1.37777778e-06,
  1.42222222e-06,
  1.46666667e-06,
  1.51111111e-06,
  1.55555556e-06,
  1.60000000e-06,
  1.10000000e-05,
  1.20000000e-05,
  1.30000000e-05,
  1.40000000e-05,
  1.50000000e-05,
  1.60000000e-05,
  2.26666667e-06,
  2.31111111e-06,
  2.35555556e-06,
  2.40000000e-06,
  2.44444444e-06,
  2.48888889e-06,
};

const double pylith::materials::PowerLaw3DTimeDepData::_density[] = {
  2.50000000e+03,
  2.00000000e+03,
};

const double pylith::materials::PowerLaw3DTimeDepData::_strain[] = {
  1.10000000e-04,
  1.20000000e-04,
  1.30000000e-04,
  1.40000000e-04,
  1.50000000e-04,
  1.60000000e-04,
  4.10000000e-04,
  4.20000000e-04,
  4.30000000e-04,
  4.40000000e-04,
  4.50000000e-04,
  4.60000000e-04,
};

const double pylith::materials::PowerLaw3DTimeDepData::_stress[] = {
  1.12311566e+07,
  1.16362430e+07,
  1.20413293e+07,
  4.33417161e+06,
  4.73925792e+06,
  5.14434423e+06,
  5.97822104e+06,
  6.03098177e+06,
  6.08374250e+06,
  2.50398815e+06,
  2.55674888e+06,
  2.60950961e+06,
};

const double pylith::materials::PowerLaw3DTimeDepData::_elasticConsts[] = {
  6.74326515e+10,
  2.25336742e+10,
  2.25336742e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  6.74326515e+10,
  2.25336742e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  6.74326515e+10,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  4.48989773e+10,
  0.00000000e+00,
  0.00000000e+00,
  4.48989773e+10,
  0.00000000e+00,
  4.48989773e+10,
  8.63434339e+09,
  2.88282694e+09,
  2.88282967e+09,
  2.58955779e+05,
  2.64412072e+05,
  2.69868365e+05,
  8.63434587e+09,
  2.88282860e+09,
  1.45530654e+05,
  1.48596941e+05,
  1.51663274e+05,
  8.63434596e+09,
  3.20600346e+04,
  3.27355228e+04,
  3.34110111e+04,
  5.74612223e+09,
 -5.50963872e+06,
 -5.62332564e+06,
  5.74589214e+09,
 -5.74174896e+06,
  5.74565739e+09,
};

const double pylith::materials::PowerLaw3DTimeDepData::_initialStress[] = {
  2.10000000e+04,
  2.20000000e+04,
  2.30000000e+04,
  2.40000000e+04,
  2.50000000e+04,
  2.60000000e+04,
  5.10000000e+04,
  5.20000000e+04,
  5.30000000e+04,
  5.40000000e+04,
  5.50000000e+04,
  5.60000000e+04,
};

const double pylith::materials::PowerLaw3DTimeDepData::_initialStrain[] = {
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
  0.00000000e+00,
};

const double pylith::materials::PowerLaw3DTimeDepData::_stateVarsUpdated[] = {
  4.08854078e-05,
  4.19057121e-05,
  4.29260165e-05,
  4.42184086e-05,
  4.52387129e-05,
  4.62590172e-05,
  1.12311566e+07,
  1.16362430e+07,
  1.20413293e+07,
  4.33417161e+06,
  4.73925792e+06,
  5.14434423e+06,
  1.09685691e-05,
  1.19823316e-05,
  1.29960941e-05,
  1.46548344e-05,
  1.56685969e-05,
  1.66823594e-05,
  5.97822104e+06,
  6.03098177e+06,
  6.08374250e+06,
  2.50398815e+06,
  2.55674888e+06,
  2.60950961e+06,
};

pylith::materials::PowerLaw3DTimeDepData::PowerLaw3DTimeDepData(void)
{ // constructor
  dimension = _dimension;
  numLocs = _numLocs;
  numProperties = _numProperties;
  numStateVars = _numStateVars;
  numDBProperties = _numDBProperties;
  numDBStateVars = _numDBStateVars;
  numPropsQuadPt = _numPropsQuadPt;
  numVarsQuadPt = _numVarsQuadPt;
  lengthScale = _lengthScale;
  timeScale = _timeScale;
  pressureScale = _pressureScale;
  densityScale = _densityScale;
  dtStableImplicit = _dtStableImplicit;
  numPropertyValues = const_cast<int*>(_numPropertyValues);
  numStateVarValues = const_cast<int*>(_numStateVarValues);
  dbPropertyValues = const_cast<char**>(_dbPropertyValues);
  dbStateVarValues = const_cast<char**>(_dbStateVarValues);
  dbProperties = const_cast<double*>(_dbProperties);
  dbStateVars = const_cast<double*>(_dbStateVars);
  properties = const_cast<double*>(_properties);
  stateVars = const_cast<double*>(_stateVars);
  propertiesNondim = const_cast<double*>(_propertiesNondim);
  stateVarsNondim = const_cast<double*>(_stateVarsNondim);
  density = const_cast<double*>(_density);
  strain = const_cast<double*>(_strain);
  stress = const_cast<double*>(_stress);
  elasticConsts = const_cast<double*>(_elasticConsts);
  initialStress = const_cast<double*>(_initialStress);
  initialStrain = const_cast<double*>(_initialStrain);
  stateVarsUpdated = const_cast<double*>(_stateVarsUpdated);
} // constructor

pylith::materials::PowerLaw3DTimeDepData::~PowerLaw3DTimeDepData(void)
{}


// End of file
